/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: andree (https://sketchfab.com/maestronoov)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bed-ea1152935b9049e4a0fcc949ebd31fa1
title: Bed
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Bed(props) {
  const { nodes, materials } = useGLTF("./glbFile/bed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./glbFile/bed.glb");
