/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: vilsonpistori (https://sketchfab.com/vilsonpistori)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/table-and-chairs-2aee19db562b4b26a199a81e62760109
title: Table and chairs
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function ChairAndTable(props) {
  const { nodes, materials } = useGLTF("./glbFile/ChairAndTableModel.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Mesa_Mesa_e_cadeira_0.geometry}
              material={materials.Mesa_e_cadeira}
            />
          </group>
          <group
            position={[-86.58, 38.02, 0.28]}
            rotation={[-Math.PI / 2, 0, -0.05]}
            scale={100}
          >
            <mesh
              geometry={nodes.Cadeira_Mesa_e_cadeira_0.geometry}
              material={materials.Mesa_e_cadeira}
            />
          </group>
          <group
            position={[-31.3, 38.02, -54.01]}
            rotation={[-Math.PI / 2, 0, -1.5]}
            scale={100}
          >
            <mesh
              geometry={nodes.Cadeira001_Mesa_e_cadeira_0.geometry}
              material={materials.Mesa_e_cadeira}
            />
          </group>
          <group
            position={[31.88, 38.02, -55]}
            rotation={[-Math.PI / 2, 0, -1.69]}
            scale={100}
          >
            <mesh
              geometry={nodes.Cadeira002_Mesa_e_cadeira_0.geometry}
              material={materials.Mesa_e_cadeira}
            />
          </group>
          <group
            position={[85.84, 38.02, -1.37]}
            rotation={[-Math.PI / 2, 0, -3.07]}
            scale={100}
          >
            <mesh
              geometry={nodes.Cadeira003_Mesa_e_cadeira_0.geometry}
              material={materials.Mesa_e_cadeira}
            />
          </group>
          <group
            position={[33.19, 38.02, 56.54]}
            rotation={[-Math.PI / 2, 0, 1.66]}
            scale={100}
          >
            <mesh
              geometry={nodes.Cadeira004_Mesa_e_cadeira_0.geometry}
              material={materials.Mesa_e_cadeira}
            />
          </group>
          <group
            position={[-28.67, 38.02, 55.56]}
            rotation={[-Math.PI / 2, 0, 1.51]}
            scale={100}
          >
            <mesh
              geometry={nodes.Cadeira005_Mesa_e_cadeira_0.geometry}
              material={materials.Mesa_e_cadeira}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./glbFile/ChairAndTableModel.glb");
