/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Karlos (https://sketchfab.com/Karldashian)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/gaming-chair-free-download-bcb13eb7ef9e4c3c9499aacff6c79757
title: Gaming Chair [FREE DOWNLOAD]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Chair_game(props) {
  const { nodes, materials } = useGLTF('./glbFile/chair_game.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.45, 347.72, -16.46]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.Plane_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0.45, 207.53, 71.02]} rotation={[-Math.PI / 2, 0, 0]} scale={83.56}>
            <mesh geometry={nodes.Plane001_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.Plane001_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0.45, 148.16, 100.43]} rotation={[-Math.PI / 2, 0, 0]} scale={[18.69, 58.11, 10.38]}>
            <mesh geometry={nodes.Plane002_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[0.45, 148.16, 100.43]} rotation={[-Math.PI / 2, 0, 0]} scale={10.16}>
            <mesh geometry={nodes.Circle_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[0.45, 151.28, 100.43]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.57, 8.57, 22.59]}>
            <mesh geometry={nodes.Circle001_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[0.45, 66, 99.64]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[8.18, 5.51, 8.18]}>
            <mesh geometry={nodes.Plane003_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[1.23, 47.51, 208.3]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[-8.98, 8.98, 8.98]}>
            <mesh geometry={nodes.Circle002_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[102.83, 47.51, 136.07]} rotation={[0, -Math.PI / 9, -Math.PI / 2]} scale={[-8.98, 8.98, 8.98]}>
            <mesh geometry={nodes.Circle003_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[69.7, 47.51, 15.89]} rotation={[0, 0.87, -Math.PI / 2]} scale={[-8.98, 8.98, 8.98]}>
            <mesh geometry={nodes.Circle004_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-70, 47.51, 16.89]} rotation={[-Math.PI, 0.87, Math.PI / 2]} scale={[-8.98, 8.98, 8.98]}>
            <mesh geometry={nodes.Circle005_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-101.4, 47.51, 137.53]} rotation={[Math.PI, -Math.PI / 9, Math.PI / 2]} scale={[-8.98, 8.98, 8.98]}>
            <mesh geometry={nodes.Circle006_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[0.45, 132.15, 100.43]} rotation={[-Math.PI / 2, 0, 0]} scale={36.1}>
            <mesh geometry={nodes.Plane004_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-107.03, 107.39, 124.38]} rotation={[-Math.PI / 2, -0.2, 0]} scale={12.6}>
            <mesh geometry={nodes.Plane005_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[433.5, 214, 1182.6]} rotation={[Math.PI, 1.2, -3.12]} scale={100} />
          <group position={[0.45, 447.8, 100.43]} scale={100}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0.45, 368.44, -8.99]} scale={6.09}>
            <mesh geometry={nodes.aseito_logo_aseito_logo_0.geometry} material={materials.aseito_logo} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./glbFile/chair_game.glb')
