/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Katerina Novakova (https://sketchfab.com/KaterinaNovakova)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/day-21-killer-furniture-06024979a503424f99b23e00bba766d1
title: Day 21: Killer Furniture
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Chair_long_blue(props) {
  const { nodes, materials } = useGLTF('./glbFile/chair_long_blue.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0.06]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
          </group>
          <group position={[0, -0.01, 0.09]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.Material} />
          </group>
          <group position={[0, -0.01, 0.09]}>
            <mesh geometry={nodes.Object_8.geometry} material={materials.Material} />
          </group>
          <group position={[0, 0.34, 0.48]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials.Material} />
          </group>
          <group position={[-0.25, 0, -2.03]}>
            <mesh geometry={nodes.Object_12.geometry} material={materials.Backdrop} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./glbFile/chair_long_blue.glb')
