/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DuduPav (https://sketchfab.com/DuduPav)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dark-wood-chair-free-ccd83fb485334e0cbd7ea27cfd65614f
title: Dark wood chair (FREE)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Chairwood(props) {
  const { nodes, materials } = useGLTF("./glbFile/dark_wood_chair_free (1).glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Chair_Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Chair_Wood}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./glbFile/dark_wood_chair_free (1).glb");