/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SonerTIFTIK (https://sketchfab.com/SonerTIFTIK)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tv-unit-furniture-cfb211faac924b978f3d0f6bc10cd55f
title: TV UNIT | FURNITURE
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function shelf_tv(props) {
  const { nodes, materials } = useGLTF('./glbFile/shelf_tv.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[13.91, 31.89, -27.98]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Box024_Material_#5_0'].geometry} material={materials.Material_5} />
          </group>
          <group position={[14.52, 102.4, 6.92]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -63.5, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes['Box020_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
            <group position={[0, 0, -48.5]}>
              <mesh geometry={nodes['Box021_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
            <group position={[0, 0, 45.5]}>
              <mesh geometry={nodes['Box018_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
            <group position={[0, 60.5, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes['Box019_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
          </group>
          <group position={[18.54, 100.89, 7.52]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -89, -1.5]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes['Box016_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
            <group position={[0, 86, -1.5]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes['Box015_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
            <group position={[0, 0, 66]}>
              <mesh geometry={nodes['Box017_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
          </group>
          <group position={[13.71, 31.89, 43.02]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Box025_Material_#5_0'].geometry} material={materials.Material_5} />
          </group>
          <group position={[1.54, 4.31, 51.52]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Box005_Material_#5_0'].geometry} material={materials.Material_5} />
          </group>
          <group position={[-28.98, 15.1, 54.52]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-1, 0, -1]}>
              <mesh geometry={nodes['Box012_Material_#6_0'].geometry} material={materials.Material_6} />
            </group>
            <group position={[0, -4.5, -1]}>
              <mesh geometry={nodes['Box013_Material_#6_0'].geometry} material={materials.Material_6} />
            </group>
            <group position={[0, 4.5, -1]}>
              <mesh geometry={nodes['Box014_Material_#6_0'].geometry} material={materials.Material_6} />
            </group>
          </group>
          <group position={[-28.97, 15.1, -38.84]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -4.5, -1]}>
              <mesh geometry={nodes['Box010_Material_#6_0'].geometry} material={materials.Material_6} />
            </group>
            <group position={[0, 4.5, -1]}>
              <mesh geometry={nodes['Box011_Material_#6_0'].geometry} material={materials.Material_6} />
            </group>
            <group position={[-1, 0, -1]}>
              <mesh geometry={nodes['Box009_Material_#6_0'].geometry} material={materials.Material_6} />
            </group>
          </group>
          <group position={[1.54, 4.31, -36.48]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Box002_Material_#5_0'].geometry} material={materials.Material_5} />
          </group>
          <group position={[-25.5, 0.89, 6.52]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['ChamferBox004_Material_#5_0'].geometry} material={materials.Material_5} />
          </group>
          <group position={[1.04, 0.89, 96.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['ChamferBox002_Material_#5_0'].geometry} material={materials.Material_5} />
          </group>
          <group position={[1.04, 0.89, 7.52]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Box008_Material_#5_0'].geometry} material={materials.Material_5} />
          </group>
          <group position={[1.04, 28.89, 7.52]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Box007_Material_#5_0'].geometry} material={materials.Material_5} />
          </group>
          <group position={[31.54, 0.89, 7.52]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['ChamferBox003_Material_#5_0'].geometry} material={materials.Material_5} />
          </group>
          <group position={[1.04, 0.89, -80.98]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['ChamferBox001_Material_#5_0'].geometry} material={materials.Material_5} />
          </group>
          <group position={[13.72, 41.62, 7.4]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['ChamferBox005_Material_#7_0'].geometry} material={materials.Material_7} />
          </group>
          <group position={[17.68, 124.73, 7.67]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-0.05, 73.95, -42.18]}>
              <mesh geometry={nodes['Box030_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
            <group position={[-0.05, 75.02, -1.71]}>
              <mesh geometry={nodes['Box029_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
            <group position={[0.05, 35.65, 26.18]} rotation={[0, 0, Math.PI / 2]}>
              <mesh geometry={nodes['Box027_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
            <group position={[0.05, -35.35, 26.18]} rotation={[0, 0, Math.PI / 2]}>
              <mesh geometry={nodes['Box026_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
            <group position={[-0.05, -73.85, -1.71]}>
              <mesh geometry={nodes['Box031_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
            <group position={[-0.05, -74.02, -42.18]}>
              <mesh geometry={nodes['Box032_Material_#5_0'].geometry} material={materials.Material_5} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./glbFile/shelf_tv.glb')
