/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: JLRIN (https://sketchfab.com/JLRIN)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tv-unit-jackdaw-d04b56eb275346478a60f60316c2c435
title: TV Unit - JACKDAW
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Shelf_TV2(props) {
  const { nodes, materials } = useGLTF('./glbFile/shelf_TV2.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.25, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['TV_Unit_-_JACKDAW']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./glbFile/shelf_TV2.glb')
