/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Blender3D (https://sketchfab.com/Blender3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/simple-tall-shelf-b46803ba0bc64e12b31f832fb761c4e0
title: Simple Tall Shelf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function simple_tall_shelf(props) {
  const { nodes, materials } = useGLTF('./glbFile/simple_tall_shelf.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.None} />
      </group>
    </group>
  )
}

useGLTF.preload('./glbFile/simple_tall_shelf.glb')
